### ISSUE TITLE
Wrong dependencies listed in readme

### ISSUE THREAD

**Issue by Suseika** [martin-tornqvist/ia#100]
In Debian Sid, I couldn't compile the game from master branch with `libsdl1.2-*`. I had to install `libsdl2-dev`, `libsdl2-image-dev` and `libsdl2-mixer-dev` (which are not in the dependencies list) in order to compile the game.

**Comment by martin-tornqvist** [comment]
Ah yes. I migrated to sdl 2. Forgot about the readme. Thanks.

**Comment by martin-tornqvist** [comment]
Updated the readme for sdl2: 1a750eb23829b886ad125af06591fd991d6602a8
