### ISSUE TITLE
Reading an Opening scroll crashes game

### ISSUE THREAD

**Issue by geffrod** [martin-tornqvist/ia#101]
Developer build crashes immediately after text telling the player that chests have opened.
![here](https://boards.fireden.net/foolfuuka/boards/vg/image/1449/45/1449454271770.png)
This problem dates as far back as Dec. 6 or possibly further.

**Comment by martin-tornqvist** [comment]
Fixed by 4df3355b3171945ede1e7aaa2b541c63eb1eb303
