### ISSUE TITLE
Trap triggers after being disarmed

### ISSUE THREAD

**Issue by hubertig** [martin-tornqvist/ia#102]
A confusion trap kept triggering after I disarmed it. I was confused and before tried disarming it while encumbered.

**Comment by martin-tornqvist** [comment]
That's strange. Traps should be completely removed/deleted when disarmed, so it's not a good sign if it's still doing stuff afterwards :-/

I'm gonna have to play around with this myself and see what happens.

**Comment by martin-tornqvist** [comment]
Note: the game doesn't allow you to disarm traps while encumbered, so this should not be relevant at all.

**Comment by martin-tornqvist** [comment]
I can't recreate the scenario you described. Are you sure you really disarmed it, and that the triggered trap was actually in that cell? There's usually a few turns delay now from when the trap activates until it actually triggers - maybe it was an adjacent trap that triggered after you stepped into the cell of the old trap?

**Comment by hubertig** [comment]
I can't tell for sure perhaps there were two same traps adjacent. Perhaps
best to ignore this. If it happens again, I'll let you know.

---
sent from schlaufon

**Comment by martin-tornqvist** [comment]
Alright, thanks. I'm leaving this issue open for a while, and will watch the traps more carefully. I'll close it eventually if I don't see any wrong behavior.

**Comment by martin-tornqvist** [comment]
OK I think it's been long enough that I've not encountered this - closing.
