### ISSUE TITLE
Request: auto-quiver thrown weapons

### ISSUE THREAD

**Issue by hubertig** [martin-tornqvist/ia#103]
They are auto-equipped when picked up while at least one of the type is already quivered.
But if I for example throw all my throwing knives and then pick them up again I need to equip them again.

**Comment by martin-tornqvist** [comment]
The problem with this is that there are lots of throwable items such as melee weapons and potions, that I don't think you'd want to auto equip in the throwing slot on pickup. Although I guess only items which are primarily throwing weapons (type == Item_type::throwing_wpn) could be auto equipped.

**Comment by hubertig** [comment]
Hey, I'm mainly referring to those items i had equipped but thrown them
all.

---
sent from schlaufon

**Comment by martin-tornqvist** [comment]
Items of throwing weapon type (throwing knives, rocks, etc) are now auto-equipped when picked up with empty throwing slot: e14991728725535c83e06b335f542a65e8aa2ef3
