### ISSUE TITLE
phobia of open places triggered while in smoke

### ISSUE THREAD

**Issue by hubertig** [martin-tornqvist/ia#104]
while wearing a gas mask in case it's relevant.

**Comment by hubertig** [comment]
also while blind

**Comment by martin-tornqvist** [comment]
Hm, yeah I guess the criteria for standing in an open place should be that all of the cells around you can be seen through.

Not sure about blindness though. I don't think being blind should protect you from this phobia. If anything, it should probably make it worse.

**Comment by martin-tornqvist** [comment]
Fixed (better late than never eh?): https://github.com/martin-tornqvist/ia/commit/0e46651de1a8b66960e12daef25e9e252b33ffa9
