### ISSUE TITLE
Request: show status of monster in description or better when looking (v) at it

### ISSUE THREAD

**Issue by hubertig** [martin-tornqvist/ia#106]
E.g., I just threw a molotov into a room knowing there was a leng spider around. When I then saw it, it was unclear whether it's burning or not. I guess the color indicates it, but I feel showing it in the description would be better. also stuff like terrified, etc...

**Comment by martin-tornqvist** [comment]
Can do.

I'll see if it's possible to show it in the initial "v" display, or if it needs to be in the detailed description page.

**Comment by martin-tornqvist** [comment]
Monster description page now shows properties: 8c086850f5a3be7f7550cf3dd0dcc83bff66d4f5
