### ISSUE TITLE
Amulet of burden also heavy when carried

### ISSUE THREAD

**Issue by hubertig** [martin-tornqvist/ia#107]
Hi, not sure if that is intended. In the text is says "it burdens the wearer", well...
I wasnt able to check, but perhaps it's only heavy after its identification; that would mean it should auto-id when picked up and not when equipped.

**Comment by martin-tornqvist** [comment]
Agreed, it's really inconsistent as it is now.

Another option is that it should only weigh a lot while equipped (which is what the description says anyway). I'll have to consider which way is best (only high weight while equipped, or always while carried)

**Comment by martin-tornqvist** [comment]
I changed it so that amulets with this effect are now always heavy, and the effect is always identified. Also made it somewhat less heavy (just "medium" weight, instead of average between "medium" and "heavy").

Implemented in 763c9b6fc855869671f601592ffcd05fd20decb9

**Comment by hubertig** [comment]
Cool, i think that's the best solution
