### ISSUE TITLE
Overlapping actors

### ISSUE THREAD

**Issue by nikheizen** [martin-tornqvist/ia#110]
When opening a tomb, I got the message 'the air feels colder.'
Then the game crashed with the following message:

> Program: ~/roguelikes/ia/ia.exe
> File: D:/dev/ia.git/src/game_time.cpp
> 
> Expression: new_actor_p != old_actor_p

System is windows 7. Game version is 18.0

**Comment by martin-tornqvist** [comment]
Yes I'm aware of this issue (but decided it was not reason enough to withhold the release of v18). It's good to have an issue for it though - it definitely needs some attention.

**Comment by martin-tornqvist** [comment]
Well, your bug turned out to be completely different from the one I thought it was. The problem with your bug was that the Tombs were a bit "heavy handed" when spawning monsters (didn't check if another monster was standing on the tomb).

Fixed by 507feaa04d5d8c25017815c4f5f0332ea596d418
