### ISSUE TITLE
Player should not telepathically see allies

### ISSUE THREAD

**Issue by Lain-** [martin-tornqvist/ia#111]
I noticed this with the Ghoul background, my character can see and hear his spawned Worm Mass (displayed as ! with green background) without direct line-of-sight. This probably shouldn't happen.

Probably applies to friendly creatures in general too, not just Worm Mass from the Ghoul background.

**Comment by martin-tornqvist** [comment]
Yes it applies to all allied creatures, and it's by design. But I agree it doesn't really make sense; I don't even know why I did it like that.

I'll update so you aren't telepathically aware of them.

**Comment by martin-tornqvist** [comment]
Fixed by: f3d8d0c47f959058ee701bb6732114915ad0a543
