### ISSUE TITLE
Corpse bashing should prioritize reviving monsters

### ISSUE THREAD

**Issue by geffrod** [martin-tornqvist/ia#112]
While trying to bash corpses that will arise soon, often one will auto-target less important things in the same corpse pile first- like mamba (all the snakes, perhaps?) corpses. Will update with specifics if I can manage to get it again. 
edit. Although, this might make for a neat feature to go with phobias- making the rush for the fearless trait (that) much more important.

**Comment by martin-tornqvist** [comment]
Added Zombie prio when bashing/eating corpses: 5fc55eb0b31b47efa5c1789265af57b4df0d0389
