### ISSUE TITLE
Potion of Clairvoyance sometimes doesn't reveal staircase

### ISSUE THREAD

**Issue by bradtmoore** [martin-tornqvist/ia#114]
Not sure if this is a bug or a feature.  I used a Potion of Clairvoyance on lvl 26 and the staircase was not revealed.

**Comment by martin-tornqvist** [comment]
This happens when the stairs spawn in dark areas. Clairvoyance doesn't reveal dark areas in the current implementation.

(This is somewhat affected by how #142 is handled)

**Comment by martin-tornqvist** [comment]
This is no longer an issue.
