### ISSUE TITLE
SDL error on launch (Linux)

### ISSUE THREAD

**Issue by tukkek** [martin-tornqvist/ia#115]
Hello, upon running the Linux binary (version 18.1) I received an error about libSDL2.2.0 not being present in my system, which really wasn't installed. I proceeded to install it (on Debian, using apt-get) and after that still got the same error and the game still won't start.

**Comment by martin-tornqvist** [comment]
I think you need libsdl2-2.0-0, libsdl2-image-2.0-0, and libsdl2-mixer-2.0-0.

Closing the issue.
