### ISSUE TITLE
XP for seeing monsters again

### ISSUE THREAD

**Issue by hubertig** [martin-tornqvist/ia#119]
this refers to 18.2:
I noticed that I gained XP for seeing monsters again after previously seeing them before.
I assume this is not intended, but I do not know this.
I noticed in this scenario:
3 snakes appear (trap)
I get blinded and run away
I wait out blindness and go back to see them unaware and level up.

**Comment by martin-tornqvist** [comment]
Are you sure you didn't just "new" monsters when you came back? Because I can't recreate this at all. Or maybe some monster died on the map and gave you XP (it could've been poisoned, burning, walked into a trap, or fighting a monster allied to you for example).

**Comment by hubertig** [comment]
I'm sure it were previously seen monsters. It happened two more times, again when triggering a level up. It might be that I used "cloud minds" on these monsters.

**Comment by martin-tornqvist** [comment]
So just to be 100% clear - you get XP twice for *seeing* them twice? Because you should get XP once for seeing them, and once for killing them (you get half their "worth" for seeing, and half for killing).

I'm experimenting with cloud minds, but I cannot recreate anything.

Does it only happen with snakes from the floor, or did you see it with other monsters as well?

**Comment by hubertig** [comment]
I did not check my XP. What I observed was that I see an unwary monster, get out of LOS, go back and level up. No other monsters involved. But perhaps cloud minds. I dont remember which monsters.

**Comment by martin-tornqvist** [comment]
Hm, well I can't recreate it, but I'll keep my eyes open for it. I still think the theory that a monster died to a trap or something somewhere could be an explanation though (although if you're seeing this repeatedly, exactly when you step into line of sight, it's getting unlikely of course).

**Comment by martin-tornqvist** [comment]
Well, this is no longer applicable, since you no longer gain XP from monsters at all.
