### ISSUE TITLE
Traps should always be revealed when triggered

### ISSUE THREAD

**Issue by hubertig** [martin-tornqvist/ia#122]

**Comment by martin-tornqvist** [comment]
Hmmm... this is by design. It's supposed to make things more challenging. But perhaps it's just annoying?

**Comment by hubertig** [comment]
imo yes, because the player knows and will just have to spend turns to search before disarming.
it's also odd that the character does not know of a trap he stumbled into.

**Comment by martin-tornqvist** [comment]
Well, you could be aware that you stepped on a small pressure plate or something, but you're not sure exactly where or what. But yeah, I'm leaning towards just revealing the traps. As you say, it just forces the player to spend turns.

**Comment by martin-tornqvist** [comment]
Apparently this has already been implemented.
