### ISSUE TITLE
Bones cant be kicked

### ISSUE THREAD

**Issue by hubertig** [martin-tornqvist/ia#124]
As insanity draws nearer I find pleasure in smashing the remains of the dead, yet I keep kicking the air when aiming for bones.

**Comment by martin-tornqvist** [comment]
Hehe yeah you're right, you should be able to kick the bones - it's frustrating. It only behaves this way now because the bones aren't actually (dead) actors, they are "features", just like stone floor etc.

**Comment by martin-tornqvist** [comment]
Issue imported to GitLab
