### ISSUE TITLE
(Develop)Compiling Fails Due to Unused Variable

### ISSUE THREAD

**Issue by nikheizen** [martin-tornqvist/ia#127]
Latest develop branch on Ubuntu Xenial 16.04.

Cause of failure is in [render.cpp](https://github.com/martin-tornqvist/ia/blob/develop/src/render.cpp#L1699) "bool did_draw" is set, but unused.
Removing all three lines referring to the variable allows compilation to succeed and the game runs as expected so far.

**Comment by martin-tornqvist** [comment]
Fixed by: a8c4abca0ad1e56ae0185428f25a2122485ab1c4. Thanks!
