### ISSUE TITLE
Occultist starts with bonus XP from Preknown items

### ISSUE THREAD

**Issue by nikheizen** [martin-tornqvist/ia#128]
Very noticeable with the changes to XP. Since the occultist recognizes their potion of spirit, as well as the manuscripts for their starting spells they get some extra XP(30%) to start off with from that. This is more than a monolith!
Seems strange and is probably unintended.

**Comment by martin-tornqvist** [comment]
It is actually intended. I don't know if it's the best solution - but what's the alternative? If the Occultist did *not* start with XP for these known items - then this classes total XP potential would be lower than the other classes. That seems much worse in my opinion.

**Comment by nikheizen** [comment]
I hadn't thought about it like that, but I suppose that makes sense.
The only arguments I can think of against that would be that generally you do not find every consumable in the game as any class, and pre-knowing certain objects is an advantage in and of itself.

**Comment by martin-tornqvist** [comment]
I'm leaning towards keeping it as it is - but I'll leave the issue open for a while as a reminder to consider the best option.

**Comment by martin-tornqvist** [comment]
It's fine...
