### ISSUE TITLE
Segmentation fault upon leveling from a monolith

### ISSUE THREAD

**Issue by paguz** [martin-tornqvist/ia#129]
Got a segmentation fault when I received xp and leveled up on a monolith on sub level 3.

**Comment by martin-tornqvist** [comment]
Tackar för tipset (thanks, I'll check it out)!

**Comment by martin-tornqvist** [comment]
Cannot recreate it :-/

**Comment by martin-tornqvist** [comment]
Fixed by 9b12edf21081eac907a8f4840ebb915076b97e34
