### ISSUE TITLE
poisoned for full health from fountain

### ISSUE THREAD

**Issue by hubertig** [martin-tornqvist/ia#130]
Now that fountains might give XP, i feel obliged to drink at least once.
The last fountain killed me with poison from drinking once at full HP (16).
I wonder if that is intended?

**Comment by martin-tornqvist** [comment]
Fountains should probably either
a) have a weaker poison on the early levels, or
b) not be poisoned at all on early levels

**Comment by hubertig** [comment]
I'll add this here as it is similar in topic imo.

I just got insta-killed by a magic trap draining my 4/4 MP on DL 7 as a war veteran.
I assume insta-deaths like this are not intended?

**Comment by hubertig** [comment]
Meeting an early dust vortex is one more death sentence.

It happened to me several times that I get paralyzed, pulled in, blinded, and killed with no options after e.g. opening a door to see a dust vortex.

**Comment by hubertig** [comment]
just died for 14 HP by !poison.

**Comment by martin-tornqvist** [comment]
> just died for 14 HP by !poison.

A good strategy is to quaff id potions next to fountains. Then you're pretty much guaranteed to survive the poison.

**Comment by martin-tornqvist** [comment]
New commit: a012fc204cef19a9e18bd2184c1bbacaaeac152b

Fountains have weaker poison on earlier levels, Spirit traps never insta-kills the player.

**Comment by martin-tornqvist** [comment]
> It happened to me several times that I get paralyzed, pulled in, blinded, and killed with no options after e.g. opening a door to see a dust vortex.

Another hint - the gas mask will protect against dust vortex blinding (and against ravens). It's probably the most powerful use of this item.

**Comment by hubertig** [comment]
Cool, thanks for the hint about the gas mask and dust vortex. I tried it and noticed that the gas mask counter didnt decrease. But I'm not sure if it attempted to blind me or not.

**Comment by martin-tornqvist** [comment]
It shouldn't decrease, because the counter represents the capacity of the
filter (as the description hints at).
