### ISSUE TITLE
suggestion: make !insight id intelligently

### ISSUE THREAD

**Issue by hubertig** [martin-tornqvist/ia#134]
The game currently makes me do the following:
if I have a strange device, i will drop all un-id-ed stuff to quaff-id one potion at a time in case it's insight to have it id my device.
This is tedious but necessary for optimal play.
I thus think !insight should id selectively, e.g. devices, amulets, etc. preferred over potions, scrolls etc.
Alternatively (but i think you wont like it), the player could choose what to id.

**Comment by martin-tornqvist** [comment]
Yeah I'm aware that this probably creates tedious situations.

I'm not against letting the player choose what to id - it's probably the best way. I definitely prefer it over having the game guess what you'd want to id.

**Comment by martin-tornqvist** [comment]
You can now choose which item to identify: 57834a7855f4fa8d8c342607494067868c0baaee
