### ISSUE TITLE
Resurrect messed up inventory

### ISSUE THREAD

**Issue by hubertig** [martin-tornqvist/ia#135]
should be the latest build:
i saved on the stairs, then resurrected without closing the game.
I suddenly have a lot of additional stuff in my inventory, I am at 135% encumberance!?
I figure it's stuff i used to have but already dropped some time before.

**Comment by martin-tornqvist** [comment]
First of all - did you load a save file from a build based on another version? Save files aren't compatible between different builds/versions of the game.

**Comment by hubertig** [comment]
No, same build. I never quit the application. I saved and then loaded from the main menu.

**Comment by martin-tornqvist** [comment]
Can recreate it. It seems like you start with your normal starting items for your class, plus the items saved from your character.

I've done some huge refactoring lately, so I'm not so surprised that something like this could happen. It's probably an easy fix.

Thanks for telling me!

**Comment by martin-tornqvist** [comment]
Fixed: 75a8ddfd26656468506d7d9af1d96b9b9efc81ff
