### ISSUE TITLE
XP from Potion of Insight

### ISSUE THREAD

**Issue by hubertig** [martin-tornqvist/ia#137]
from the release history:
* Potion of Insight gives XP if there is no item to identify

I had two unknown potions of insight and no other unidentified things.
Quaffing gave me 10XP only. I guess it id-ed the other same potion!?

**Comment by martin-tornqvist** [comment]
Working as intended. Identify pots will identify one item, which gives you the XP worth for identifying that item. If you have no unidentified items it gives you 10% XP instead.

This is just added so that identity pots doesn't become worthless if you identify every item

**Comment by hubertig** [comment]
But the potion of insight was unknown to me at the time.

So for quaffing insight for the first time I should get 20XP (10XP for id-ing insight and 10XP for whatever it id-ed).
I only got 10XP for the quaff-id.

**Comment by martin-tornqvist** [comment]
Depends on how you look at it. In this case "id-ing insight", and "whatever it id-ed" is the same thing: you id-ed insight. The potion only gives 10 XP if it didn't id anything at all, but in this case it did id a potion (itself), which is worth 10 XP.

That's from a technical point of view however. From a gameplay, "fairness", or fun perspective, should you get 10 or 20 XP for id-ing insight by itself? What behavior does either option promote?

If you get 10 XP, you really want to avoid quaffing a single unknown potion, in case it's insight. You _already_ want to avoid this (so that you identify something), but now even more so. This seems bad.

So with that conclusion - okay - you should get 20 XP in this case (i.e. insight should always give you 10 XP, plus XP for identifying something, including itself).

Reopening the issue.

**Comment by martin-tornqvist** [comment]
There: 82211a904354aee6ddc8f293d9b98e7265b0ddd6

**Comment by hubertig** [comment]
I was just thinking about this issue some more.

When I quaff !insight and it identifies ?darkbolt for me, then the 10XP for identifying ?darkbolt are something I would have gotten anyways when eventually read-id-ing ?darkbolt.
This means quaffing !insight becomes better with no id-able things in the inventory, because then you get free XP. Exceptions are strange devices, but everything else would better be use-id-ed.

**Comment by hubertig** [comment]
just encountered this:
i quaff a known !insight which identifies my strange device. I gain 20XP for id-ing the device. But then I also got 10XP (I feel insightful) !?

**Comment by martin-tornqvist** [comment]
Okay, let's sort this out once and for all.

Given that identifying potions grants 10 XP, and that quaffing !insight when all items are already identified should give some bonus - how much XP should you get in each of the following situations?:

A) You quaff an unidentified !insight, while carrying one other unidentified potion (of a different type).
B) You quaff an unidentified !insight, while carrying no other unidentified items.
C) You quaff an identified !insight, while carrying one other unidentified potion (of a different type).
D) You quaff identified !insight, while carrying no unidentified items.

**Comment by hubertig** [comment]
Ok, here is what i think

A) You quaff an unidentified !insight, while carrying one other unidentified potion (of a different type).
10 XP for id insight
10 XP for id other potion
B) You quaff an unidentified !insight, while carrying no other unidentified items.
10 XP for id insight
C) You quaff an identified !insight, while carrying one other unidentified potion (of a different type).
10 XP for id other potion
D) You quaff identified !insight, while carrying no unidentified items.
0 XP
i think this has to be like that, bc otherwise you rather auto-id everything and get free XP quaffing !insight with nothing to id

**Comment by martin-tornqvist** [comment]
> i think this has to be like that, bc otherwise you rather auto-id everything and get free XP quaffing !insight with nothing to id

I don't think it has to be that way. This is how it's currently implemented (which gives bonus XP for quaffing an identified potion - to ensure that !insight never becomes worthless):

A) You quaff an unidentified !insight, while carrying one other unidentified potion (of a different type).
10 XP for id-ing other potion
10 XP for id-ing !insight

B) You quaff an unidentified !insight, while carrying no other unidentified items.
10 XP for id-ing !insight

C) You quaff an identified !insight, while carrying one other unidentified potion (of a different type).
10 XP for quaffing identified !insight
10 XP for id-ing other potion

D) You quaff identified !insight, while carrying no unidentified items.
10 XP for quaffing !identified insight

The only problem I see with this model is that it's a bit overcomplicated.

Alternatively, this model could be used (_always_ give bonus XP for quaffing !insight):

A) You quaff an unidentified !insight, while carrying one other unidentified potion (of a different type).
10 XP for quaffing !insight
10 XP for id-ing other potion
10 XP for id-ing !insight

B) You quaff an unidentified !insight, while carrying no other unidentified items.
10 XP for quaffing !insight
10 XP for id-ing !insight

C) You quaff an identified !insight, while carrying one other unidentified potion (of a different type).
10 XP for quaffing !insight
10 XP for id-ing other potion

D) You quaff identified !insight, while carrying no unidentified items.
10 XP for quaffing !insight

I like this model actually, it's nice and simple. !insight will be a really strong item, but that's fine.

**Comment by hubertig** [comment]
if !insight never losing value is important to you, then your solution seems best. making !insight stronger is good imo too.

**Comment by martin-tornqvist** [comment]
Well, it now works according to the second method above (except insight itself only gives 5% XP).
