### ISSUE TITLE
scroll of detect objects is broken

### ISSUE THREAD

**Issue by hubertig** [martin-tornqvist/ia#139]
does it show things just briefly or longer?
anyways, I saw nothing. I think it said it detected one object. in the next room i found three things already.

**Comment by martin-tornqvist** [comment]
Yes it's definitely broken.

**Comment by hubertig** [comment]
huh...the history reads that I changed the title even though you did??

**Comment by martin-tornqvist** [comment]
Another one down: 5ddd659e7691c909cd9aa7f59a11685f558c07b2

Keem 'em coming ;-)

**Comment by martin-tornqvist** [comment]
> huh...the history reads that I changed the title even though you did??

Yeah I noticed that too. Really strange. It also says "hubertig added the Critical bug" label. Seems like a bug in Github?
