### ISSUE TITLE
when blind: icon of picked up item stays on map

### ISSUE THREAD

**Issue by hubertig** [martin-tornqvist/ia#142]

**Comment by martin-tornqvist** [comment]
New commit: bb2b1cd5493e847a4cf71a9f90a676813cbb8081

When blind, you always explore your own position,
Darkness can be explored,
Dark cells are colored slightly blue

I kind of liked when dark cells remained "unexplored" though - it was very distinct which areas where dark (which is the purpose of now coloring them blue), and it gave them a bit of mystery.

But if you explore your own cell while blind, it doesn't make any sense that you can't explore cells in darkness (it gets especially silly when you're blind and cannot explore dark cells)

**Comment by hubertig** [comment]
What i meant is: i saw a potion. I become blind yet walk to it and pick it
up. But the icon showing where it is/was remains.

**Comment by martin-tornqvist** [comment]
> What i meant is: i saw a potion. I become blind yet walk to it and pick it up. But the icon showing where it is/was remains.

Yes I got that. However, if the game should show that the item is removed from the map when picked up while blind - the only way to do that is to update the player knowledge of this cell ("explore" the cell).

But - it would be weird if when you're blind you only explore cells when picking up or dropping items, and not while walking around. So to allow the game showing items being picked up or dropped, the most sensible solution is that you always see and explore the cell you stand on.

But then we run into this problem:

> But if you explore your own cell while blind, it doesn't make any sense that you can't explore cells in darkness (it gets especially silly when you're blind and cannot explore dark cells)

So logically darkness has to be explorable too.

**Comment by hubertig** [comment]
Mmmh...to be honest I do not quite understand what you mean.
I just think that the map reflects what the character knows/sees and if he knows there is a potion and picks it up, then the icon should disappear independent of whether he is blind or not imo.

**Comment by martin-tornqvist** [comment]
> if he knows there is a potion and picks it up, then the icon should disappear independent of whether he is blind or not

Yep, I agree on that, and that's what happens now.

Could you please try exploring a dark area now though, and tell me what you think? The update there is that you can actually permanently explore dark areas.

(Side note: this affects how #114 should be handled)

**Comment by hubertig** [comment]
dark areas look fine to me. maybe make the blue color a bit more distinct to easier recognize explored dark rooms. it's a really good change that you made the whole map lighter and more visible.

**Comment by martin-tornqvist** [comment]
New commit, made some improvements to how the dark areas are rendered: ed12751d5bc4e3ab9b13ff93ee5a110257ba7828

Looks really neat now imo.
