### ISSUE TITLE
Show combat statistics in monster view screen (ranged/melee hit chance, dodging, etc)

### ISSUE THREAD

**Issue by hubertig** [martin-tornqvist/ia#143]
threw 3 throwing knifes at dean halsey while he was coming towards me.
percentages showed: 99%, 85%, 90%

it was a rogue with adept ranged attack skill. but i had noticed odd numbers before

**Comment by martin-tornqvist** [comment]
There's several modifiers that affects ranged hit chance: size of the target, speed of the target, whether the target is aware of you or not, your skill, the weapon stats, if the target is stuck, or confused, etc.

What happened here was:
99%: The monster unaware of you, big hit chance bonus - you had maximum chance of hitting
85%: Now he's aware of you (actively fighting), somewhat smaller chance to hit
90%: He was one step closer to you (5% modification per step)

I know it can look a bit bewildering, but I think the numbers makes sense on the whole.

Perhaps printing this info in detail on the monster view page would clear things up.

**Comment by hubertig** [comment]
ok, now i see. thank you.
yes, i'm all for putting such info into the description. perhaps also their dodging chance for melee which seems completely invisible right now i think.

**Comment by martin-tornqvist** [comment]
Yes the monster screen could use some more statistics.

**Comment by martin-tornqvist** [comment]
Related: #157

**Comment by martin-tornqvist** [comment]
Fixed: 0ef139b6904982eece76f04bc6b97d7a5dbe972e
