### ISSUE TITLE
!clairvoyance does not reveal monolith

### ISSUE THREAD

**Issue by hubertig** [martin-tornqvist/ia#144]
but stuff like scrolls

**Comment by hubertig** [comment]
since it will show the floor pieces but not dark ones, dark rooms do not become visible with clairvoyance

**Comment by martin-tornqvist** [comment]
I'll make clairvoyance reveal dark rooms, if dark rooms should be explorable. It depends on the outcome of #142.

**Comment by martin-tornqvist** [comment]
It does reveal monoliths now. Closing the issue.
