### ISSUE TITLE
Feeding on zombie corpses should cause them to have reduced HP if they rise again

### ISSUE THREAD

**Issue by hubertig** [martin-tornqvist/ia#145]

**Comment by martin-tornqvist** [comment]
Very minor issue imo. I guess they could rise with lower health if they were fed on.

**Comment by hubertig** [comment]
yes, minor issue. just wasnt sure if it's intended or not. feeding on them decreasing their later health would be a pretty cool effect imo.

**Comment by martin-tornqvist** [comment]
Issue imported to GitLab
