### ISSUE TITLE
after taking "expert melee" my equipped hammer still showed 75% in stead of 85%

### ISSUE THREAD

**Issue by hubertig** [martin-tornqvist/ia#147]
i didnt try un- and re- equipping it at the time

**Comment by martin-tornqvist** [comment]
I cannot recreate this. Picking expert melee always adds 10% for me. Tried with different weapons, including a hammer.

I think you got wounded. Each wound decreases melee skill by 10%.

**Comment by hubertig** [comment]
Ok, that is possible; i dont remember.

**Comment by hubertig** [comment]
I'm seeing this issue again. what seems to happens is that the percentages are reduced via wounds/disease and are then not restored. i think i healed wounds with !vitality and disease with !curing.

**Comment by martin-tornqvist** [comment]
Alright, good.
