### ISSUE TITLE
make searching more consistent

### ISSUE THREAD

**Issue by hubertig** [martin-tornqvist/ia#149]
I had just spend about 400 (!) turns before i discovered a door directly next to me. with "observant" skill.

**Comment by martin-tornqvist** [comment]
Hm, I guess doors should track how many turns they have been searched for, and guarantee detecting them if this counter goes beyond a certain fixed value.

**Comment by martin-tornqvist** [comment]
I believe this is better balanced now: 25892faad9a04e35cbead2e54dbfffe4ca10b83f

Finding adjacent doors is much easier.

(I changed my mind about guaranteeing finding the door after X number of turns, I think it could encourage very boring and meta gamy behavior)
