### ISSUE TITLE
Staff of Pharaoh spell disappears if you drop and re-pickup.

### ISSUE THREAD

**Issue by Mekire** [martin-tornqvist/ia#152]
In my most recent War veteran run I had a Staff of Pharaoh.  Initially when picked up the spell became available as normal.  At one point I was rearranging my inventory unsure if I would keep it.  I dropped it, and after picking it back up the spell was no longer there.  I tried several times and the spell did not return, regardless of equipping or not.

This was in version 18.2; unsure if this has been fixed in dev or not (or if it is intentional though that seems odd).

**Comment by martin-tornqvist** [comment]
Well this is pretty bad - thanks!

**Comment by martin-tornqvist** [comment]
Fixed: 1eeae9047d845dca2c3685d5bf0ba21da623b24e
