### ISSUE TITLE
zombies walk through closed and stuck (spikes) gate

### ISSUE THREAD

**Issue by hubertig** [martin-tornqvist/ia#154]

**Comment by martin-tornqvist** [comment]
Are you sure? I cannot recreate this - they always correctly try to bash it open.

**Comment by hubertig** [comment]
Yes sure. I observed it several times in my current game.

**Comment by martin-tornqvist** [comment]
You mean they just walk though it, without bashing it?

Does it always happen? Or just rarely? Do they also try to bash it sometimes?

Do you have vision of the gate cell when they walk through it?

Are you standing adjacent to the gate on the other side?

Does it happen both when the gate is spiked and not?

Does it only happen with Gates, not with normal doors?

**Comment by martin-tornqvist** [comment]
Another thought, try running "make obj-clean", then rebuilding.

The makefile is not set up to handle dependencies to header files. It's _possible_ that the problem would go away from a fresh rebuild, although it's not likely.

**Comment by martin-tornqvist** [comment]
Yeah I don't think this is actually a thing.

**Comment by hubertig** [comment]
Hi, sorry somehow missed your comments here. it happened, but it's possible i pulled, then build again with "make clean". not sure how that could do it, but well.....it really happened though :)

**Comment by martin-tornqvist** [comment]
Yeah I believe it happened, but I think your build was in some bad state - at least that's the only explanation I can imagine at the moment.

The makefile can now detect when cpp files needs to be rebuilt due to changed hpp files, so hopefully "corrupted" builds like this are no longer possible.
