### ISSUE TITLE
shock wave device should paralyze monsters longer

### ISSUE THREAD

**Issue by hubertig** [martin-tornqvist/ia#158]
it says it does in the description

**Comment by martin-tornqvist** [comment]
It does for me. They are knocked back one step, and paralyzed.

But of course it won't push back monsters who are blocked by other monsters or by walls etc.

**Comment by hubertig** [comment]
mmh..ok, i remember it with apes who are fast so perhaps they could already move back in on me?

**Comment by hubertig** [comment]
i think i also had this with zombies, but looking back it's possible one was pushed away and another stepped in.
anyways, it would be cool if the device's wave would ensure no adjacent monsters the turn after using it.

**Comment by martin-tornqvist** [comment]
> i remember it with apes who are fast so perhaps they could already move back in on me?

Yeah that's probably it.

> anyways, it would be cool if the device's wave would ensure no adjacent monsters the turn after using it.

Perhaps knockback from the Shockwave device should paralyze the monsters longer than usual? Like three turns instead of one turn.

**Comment by martin-tornqvist** [comment]
Done: 2fd110c8c4a955cf34348a0184939b80a5d56ba5
