### ISSUE TITLE
Video 2 wins + questions.

### ISSUE THREAD

**Issue by Spoony1992** [martin-tornqvist/ia#160]
Here end-game of first win: 
https://www.youtube.com/watch?v=kdWdBqqiARY
Check comment sections for balance suggestions.
 BTW, I'm gonna be stupid with my next questions. I can't find v19 that hubertig talking about. My total playing time in this game is approximately 600 hours. After reading about Monolith usage, gates, gratings, vines, Pharaoh Staff I feel realy dumb. 
 I win this game with every class (win once in this version already), read a lot of source code, but never understand how to use Monolith and never seen gates or v19. Identifying stuff and discovering new monster types dont give me extra xp and I progress at slow rate. Like max lvl 9-10 at the end of the game without dlvl 20 farming. 
 Can you clarify this things for me? 
 Also I want to write a guide on this game? Can I publish it there?
 Edit: I captured another win with full gameplay from dlvl 1 to dlvl 32 now. I wish you increase Greater Polyp spawn rate to spice up things, because 90% of times you can never see him in the game. He must see invis too, and spawn from dlvl_last - 8. I dont farmed dlvl20 locust this time. Link:
https://www.youtube.com/watch?v=W0mtDGPKDMk&feature=youtu.be

**Comment by martin-tornqvist** [comment]
Hi,
Awesome that someone got so much enjoyment out of the game :)

The v19 you're seeking currently only exist as source code, as a work in progress. There is no official pre-built 19.0 released yet.

If you want to try it out (which I'd encourage), there are some instructions on the IA Github page for building the game (currently only supported on Linux though):
https://github.com/martin-tornqvist/ia

Scroll down to "Guide for building Infra Arcana".

Bug reporting and feedback on balance is always welcome.

I made a separate "enhancement" issue (#161) about your final comments on the Greater Polyp.
