### ISSUE TITLE
seeing snakes gives no exp

### ISSUE THREAD

**Issue by hubertig** [martin-tornqvist/ia#166]

**Comment by martin-tornqvist** [comment]
You only get XP when seeing monsters that cause shock.

**Comment by hubertig** [comment]
well, I personally would be somewhat shocked by snakes that poison, blind, or weaken me. Similarly, if some huge and deadly spider shows up :)

**Comment by martin-tornqvist** [comment]
Sure - even a pack of rats should be at least slightly unpleasant to anyone, realistically speaking. But you've gotta draw the line somewhere. My rule of thumb is that things which exist in reality, or could possibly exist as undiscovered species, do not cause shock and do not give XP for discovering.

The spitting cobras for example are just supposed to be the real animal, there is no fantasy element about them:
https://en.wikipedia.org/wiki/Spitting_cobra
