### ISSUE TITLE
onset of insanity takes 1 or 3 turns

### ISSUE THREAD

**Issue by hubertig** [martin-tornqvist/ia#167]
usually it's 3, but it just happened to me that id-quaffing a potion upped my shock and it increased insanity within 1 turn.

**Comment by martin-tornqvist** [comment]
Cannot recreate. Maybe it was a Potion of Paralyzation?

**Comment by hubertig** [comment]
i cant remember, perhaps it was. that would explain it.

**Comment by martin-tornqvist** [comment]
I'll close this issue but keeping an eye out for it.
