### ISSUE TITLE
Current viability of melee.

### ISSUE THREAD

**Issue by Mekire** [martin-tornqvist/ia#168]
I have played 18.2 extensively.  I have a War Vet win and have taken all classes pretty far into the game.  I recently reinstalled Linux on one of my machines so I thought I'd give the new developments a try.  I'm still very much adjusting to the way the new version works but wanted to share a little feedback.

In the current 18.2 release I always felt there was an interesting dichotomy between Rogue and War Vet.  In my experience rogue struggles a bit in the early game but then excels beautifully in the late game due to the need for stealth.  Conversely the War Vet always does quite well in the beginning but later on, when fighting is less viable, struggles to be unseen.  I always enjoyed this and favored the war vet approach, bashing heads in early and then trying to remain stealthy and mobile late game.

This style of play, and indeed melee in general, just doesn't seem viable anymore.  People have always claimed Rogue was the easiest win, and war vet was quite challenging, so it seems odd that war vet should get what feels like quite a nerf.  Hit rates are now much worse than they were and even the instant weapon swapping seems to be gone.  In 18.2 my favored approach to war vet is to wear lighter armor and use a sledge hammer.  Now it hardly seems that the sledge can be used in any circumstance.

Am I missing something, or are you really trying to drive home the idea that fighting (even early) just isn't really an option (in which case why have war vet to begin with)?

I do quite enjoy some of the new aesthetic touches (chains, vines, grates, etc.) and I will continue trying to adjust to this style of play.  I do however feel that my favorite style of play has been removed and am curious as to your thoughts on this.

**Comment by martin-tornqvist** [comment]
Hm, yeah that's not ideal, if there's no viable melee build at all, it makes the game less diverse. Yes I am pushing much more for making fighting something you should (and can) avoid - but the main combat class should probably still be able to hack and slash their way through, at least until mid-game.

So it seems that the War Vet should get some unique melee bonus then. Some random ideas:
* Only receives wounds when taking > 5 damage (instead of > 4 damage as for the other characters), so melee combat is less resource draining.
* Has a "natural" armor of 1 (will have exactly the same effect as the above, but also causes you to lose less HP)
* Speed bonus to all melee attacks

What do you think?

**Comment by Mekire** [comment]
It seems to me that accuracy is what is hurting the most.  For instance I just died to a raven pair after putting on the gas mask.  In 18.2 the only threat they would have posed was blindness and, once wearing the gas mask, would have been dispatched with ease.   In the current I managed to miss about 5 times in a row and die from pecks.  This was also with taking "expert melee" as my first trait.  It definitely feels... wrong.

I was also wondering why I seem to be getting massively OOD enemies even on d1.  I recently had runs with two byakhees (sp) as soon as I entered the dungeon, a color out of space, and a fire vortex.  Most of which resulted in predictable deaths.  Is this for testing purposes or are we really to expect that we can run into almost any monster on d1.

**Comment by martin-tornqvist** [comment]
>I was also wondering why I seem to be getting massively OOD enemies even on d1

Hm, what version did you build from? It was like that like a month ago (was just experimenting). But now it should be more sane. Since December 15 a Fire Vortex on dlvl 1 should definitely be impossible (see b062ba15d137dbb50d81fff7efc7de32d51e6361).

**Comment by martin-tornqvist** [comment]
Update: 61ae210e5864697d4659b14340c58892f40f4864

 Misc balancing:

* Summoning spell also capped by dlvl when monster casting
* Lowered the dodging ability for many monsters
* Slightly fewer dlvls out of depth monster spawning allowed

Please try it out with this change and see what you think. Monsters should now be somewhat easier to hit overall.

**Comment by Mekire** [comment]
> Hm, what version did you build from? 

I just cloned and built dev about two days ago.

> Please try it out with this change and see what you think. Monsters should now be somewhat easier to hit overall.

I'll check it out.

**Comment by martin-tornqvist** [comment]
This is an old discussion, a lot has changed since then - closing.
