### ISSUE TITLE
bunch of issues

### ISSUE THREAD

**Issue by hubertig** [martin-tornqvist/ia#169]
hey, I figured I'd just post all small things in one list.

- ~machete and chains were on the same floor tile and only the machete was visible. So it's like a noise trap :) I guess showing both is the only real solution?~

**Martin:** Solved by drawing with colored background when the chains are "covered" by an item or corpse: c76fd07fb26bf44a13ee07ba8ddc73f26b741e85 (traps and liquids also do this).

- ~i descended a floor, which caused two messages 1) EXP for new floor 2) terrify from insanity. However i also saw keziah but the EXP for her was only triggered the next turn.~

**Martin:** From looking at the code, monsters are discovered when your turn starts now - perhaps this was not the case before. Even if this still exists, this is extremely minor, and should also be very rare.

- ~i used sacrifice spirit but it seems the monster got to act before it took effect~

**Martin:** This spell no longer exists.

- ~i missed several times with a 99% chance aiming at a unaware bat with a spike gun~

**Martin:** Fixed: 6d916f9d6f9279ce8b38977814c91f01e4cb229a

- ~ok, this is a question :) i dont get how the veterans weapon switching works now. Does it take a turn every other time you use it? I liked the old way :)~

**Martin:** It now uses the old way (instant swapping)

**Comment by martin-tornqvist** [comment]
> machete and chains were on the same floor tile and only the machete was visible

Yeah... same thing with water. It's somewhat annoying. I think showing both would look weird. Perhaps the game could cycle between showing the chains and the item (like, switch once per second or so). Would require some game engine work - but probably not super hard.

> i descended a floor, which caused two messages 1) EXP for new floor 2) terrify from insanity. However i also saw keziah but the EXP for her was only triggered the next turn.

I'll fix it.

> i used sacrifice spirit but it seems the monster got to act before it took effect

I'm 99.9% certain that the effect took place before the monster acted. It's probably just that the interface graphics were not updated until it was your turn to act. I'll fix it.

> i missed several times with a 99% chance aiming at a unaware bat with a spike gun

I noticed a problem with this recently as well, and it's in my notes. What happens is that noisy firearms alerts the monster immediately, so when the projectile reaches them, the monster is considered to be aware. Haven't come up with a good solution to this yet, but I'll think about it. The EASIEST solution would be to remove the hit chance bonus for ranged attacks against unaware monsters - but it's probably a nice bonus to have.

> ok, this is a question :) i dont get how the veterans weapon switching works now. Does it take a turn every other time you use it? I liked the old way :)

Well, they switch with with 100% higher speed (i.e. twice as fast). You can compare it with running a certain distance in 10 seconds - if you do this with 100% higher speed (i.e. meters per second is twice as high), you do it in 5 seconds instead.

So switching weapon takes only a half standard turn.

I  could perhaps make switching instant again for the War Vet, but I think it's a little weird that switching weapon takes NO time at all. The current way is a bit more "realistic".

**Comment by hubertig** [comment]
Cool :)

The problem I have with the way switching works atm is that when i move and a new monster comes into LOS, I do not know whether I will be able to switch before it gets to act or not (it feels like 50-50).

**Comment by martin-tornqvist** [comment]
Hm, that's a good point. This is a general problem with "X% speed" time systems though (you don't know if shooting a gun will allow the monster to act either). But I guess it's especially noticeable for the weapon switching. I'll consider making it instant again for the War Vet.

**Comment by martin-tornqvist** [comment]
@hubertig  Ok, so having the game engine cycle between which object to draw is actually not really feasible at the moment. I don't think I'd ever want to do this either, since it would make the game a lot more resource hungry (constantly rendering instead of only when stuff happens - I really like that when the game is idle, it pretty much takes no CPU power, it's especially nice for people with laptops running on battery and stuff like that :-) ).

But I solved it in a different way, see the edit in your original comment.

**Comment by hubertig** [comment]
Hey, 
i havent played in a while and just started again. loving all the additions and changes. Cool to see IA still improving even though i think it's an elite RL already.

I have two comments:
- pretty often i forget about my lantern being "on" and that sucks. Perhaps it's status could be more visible noticeable, e.g. lit walls being yellow-ish, or the @ tile being different?
- When a zombie dies and leaves a corpse. then this corpse is not directly visible if on a tile with eg a stone
- not 100% sure it's still the case, but i think so: i dont like dynamite not killing zombies fully (ie no corpses), also (again from memory) dynamite would not destroy altars, braziers, ... which is odd too.
- just a funny thing: "blind and terrified i move one round to another cardrige" lol :)

Thanks for making this great game!

**Comment by hubertig** [comment]
minor things:
- traps are discovered whenever a monster leaves its corpse on that tile
- it seems the sledgehammer cannot be used to open chests
