### ISSUE TITLE
sight and darkness

### ISSUE THREAD

**Issue by hubertig** [martin-tornqvist/ia#172]
There is a non-intuitive thing about vision when in darkness

##########
@ . . . / . . . . 
##########

/ : open door
left of the door is darkness
right of the door are lit tiles

when looking at the above situation, @ cannot see the lit corridor ahead, because there are tiles of darkness in between.

**Comment by martin-tornqvist** [comment]
Really? I could have sworn that you can see "out of darkness" into non-dark or lit cells on the other side.

I will have to investigate this.

**Comment by hubertig** [comment]
http://imgur.com/a/rmdjk

**Comment by hubertig** [comment]
probably related light issue: lantern wont shine into darkness through bars
[http://imgur.com/a/hPL1Y](url)

**Comment by martin-tornqvist** [comment]
> probably related light issue: lantern wont shine into darkness through bars

Strange, I'm not experiencing this issue at all. Are you sure the lantern wasn't malfunctioning ("flickering") in that screen shot? That would explain what you see there.

Here's a screen shot of the lantern shining through bars, into a dark room.

![screenshot_2017-05-17_22-35-32](https://cloud.githubusercontent.com/assets/1785363/26174930/3d4cbb72-3b51-11e7-80be-737b81ce052d.png)

**Comment by hubertig** [comment]
yes, thats weird. im playing latest developer on linux 64.
in my screenshot above there was a hidden door left of the bars. i opened it and could not light the room behind it until i stepped on the tile of the door.

**Comment by martin-tornqvist** [comment]
Regarding your first issue - I realized that this is actually intended. You can only see "out of darkness" into **lit** cells - not into "neutral" cells.

A cell can have brightness level normal, dark, or lit.
