### ISSUE TITLE
rework throwing

### ISSUE THREAD

**Issue by hubertig** [martin-tornqvist/ia#173]
I think it would be best to not have a dedicated throwing slot, but instead be able to throw anything in 1 turn

Problems i have currently:
- negative potions are more or less useless given a) their relatively high weight and b) that it would take 3 turns (unequip, equip, throw) to use them (also applies to zombie dust)
- i can quaff a potion in 1 turn, why cant i throw one in 1 turn?

I'd suggest either doing it similar to crawl (t for throw and optionally cycle through possible ammo) or like brogue (t for throw, then select item from inventory)

**Comment by martin-tornqvist** [comment]
I agree 100% with this. Throwing in is something I've considered to be pretty annoying in IA for a long time, and I have an old TODO about reworking it. It's time to fix this now.

I'll look more into how Crawal and Brogue does it - they tend to be good examples when it comes user interface stuff.

**Comment by hubertig** [comment]
i guess this is related:
when i equip zombie dust in my throwing slot and then pick up new dust, it's put in my inventory instead of the throwing slot.

**Comment by martin-tornqvist** [comment]
> when i equip zombie dust in my throwing slot and then pick up new dust, it's put in my inventory instead of the throwing slot.

That sounds like a bug. But it doesn't matter - I've removed the throwing slot now anyway. You will simply select the item to throw when you press t. I think it works great.

**Comment by martin-tornqvist** [comment]
There, the throwing slot is gone now: b0f339a24a11cb890523f364552595c163c7f9df

Let me know what you think!

There is one issue remaining though - there is now a bunch of empty space on the info lines at the bottom of the screen (where the throwing weapon used to be shown), which I don't know what to do with.
I guess I could start showing the status effects (diseased, blind, etc) on the second line already - so they get about one and a half lines of space.

**Comment by hubertig** [comment]
right now it seems very tedious to me. when i start a new game and want to throw a throwing knife, pressing "t" offers the weapon i'm wielding first, so "b" for the knives, then aim. for every time i want to throw a knife.
I think that as long as the last throwing option is a stack, pressing "t" should go to aiming just as before but with an option to press somekey to choose another option.
the recently won space on the bottom could be filled again with the currently selected default option :)

**Comment by martin-tornqvist** [comment]
Maybe "T" should open a menu for choosing current throwing weapon? And if no weapon is currently selected, "t" will also open this menu. Otherwise if you already have a weapon chosen, pressing "t" will aim it.

**Comment by martin-tornqvist** [comment]
Ok, now I've implemented and pushed the method I proposed in my previous comment. Try it out!

**Comment by martin-tornqvist** [comment]
I think this works well now.
