### ISSUE TITLE
seg fault on linux 64

### ISSUE THREAD

**Issue by hubertig** [martin-tornqvist/ia#174]
seg faults right off the bat.
i did a checkout of "Throwing weapon selectable by pressing "T"" and that works.

**Comment by martin-tornqvist** [comment]
This may be because I changed the format of the config file recently. Try
deleting the config file in the res/data folder so that default settings
are loaded.

**Comment by hubertig** [comment]
cant confirm that that was the reason. i cloned a new repository and it worked, so you're probably right.
thanks!
