### ISSUE TITLE
#include <numeric> in rl_utils.cpp?

### ISSUE THREAD

**Issue by garnik-ananikyan** [martin-tornqvist/ia#179]
Had the following error trying to compile the master branch under osx:
```
rl_utils/src/rl_utils.cpp:340:26: error: no member named 'accumulate' in namespace 'std'
    const int sum = std::accumulate(begin(weights), end(weights), 0);
```

Fixed by adding `#include <numeric>` line to the rl_utils.cpp. 
Not really sure if it's a legitimate issue or if I just did something wrong while cloning the branch (I barely know what I'm doing), but could be helpful.

**Comment by martin-tornqvist** [comment]
You're probably right. I've seen this several times before (header include needed to build on some systems but not on others). I'll add it.

**Comment by martin-tornqvist** [comment]
No, wait - your error message looks weird. There's no call to "accumulate" in rl_utils.cpp. However, there was such a call about a year ago, before I split stuff into separate source files.

You should try running `git pull`, and then `git submodule update` from the ia root directory.
