### ISSUE TITLE
Discovering Gas Spores does not give XP

### ISSUE THREAD

**Issue by iamstevevan** [martin-tornqvist/ia#180]
Reading the def, this creature has no shock value.  Imagining a floating ball of fire-gas, this creature is frightening, if not terrifying.

**Comment by martin-tornqvist** [comment]
Agreed. I'll add a shock value for them.

**Comment by iamstevevan** [comment]
Frighteningly good news!

**Comment by martin-tornqvist** [comment]
Fixed: 50e04265a2bfdfc025fd14dbd50df5792c663fde
