### ISSUE TITLE
"Suddenly, the walls collapse" CRASHES the game. v19.0 Windows

### ISSUE THREAD

**Issue by Tranquil-Suit** [martin-tornqvist/ia#181]

**Comment by martin-tornqvist** [comment]
OK, this has existed for multiple versions now - it's really time to do something about it (although it does not happen **every** time, and I actually don't think I've ever seen it myself - but I've heard about it several times).

Thanks for reporting.

**Comment by martin-tornqvist** [comment]
OK, I'm fairly sure I've fixed this bug now: 10720b2a641afe0f0563593086c744cf916b213c
