### ISSUE TITLE
scroll of insight did not id other unknown scroll in inventory

### ISSUE THREAD

**Issue by hubertig** [martin-tornqvist/ia#182]

**Comment by martin-tornqvist** [comment]
Did you build the game from source? Or was it 19.1-beta.1?

Did you get the message "It is a dreamless sleep"?

**Comment by hubertig** [comment]
i pulled and build today. the message was "there is a flash of light" or something.

**Comment by martin-tornqvist** [comment]
"Flash of insight".

You need to fulfill some conditions to identify something (some of these will be changed). Check the spell description.

**Comment by hubertig** [comment]
ok, will do. sorry, lots of changes. great to see you continuously improving the game. i expected it to id something in my pack.
