### ISSUE TITLE
Running behaviour

### ISSUE THREAD

**Issue by enormandeau** [martin-tornqvist/ia#188]
- If running and a door is present in one of the 8 adjacent squares, stop
- Don't stop for "I stagger" message when running
- Allow starting to run on vines, water, mud if that type is directly adjacent (the player WANTS to start running in that direction, so no point in dis-allowing it)
- Continue running as long as nothing happens
- Turn corners in corridors? That would be cool.

**Comment by enormandeau** [comment]
- Continue running as long as nothing happens

**Comment by enormandeau** [comment]
- Turn corners in corridors? That would be cool.

**Comment by martin-tornqvist** [comment]
Most of these are fixed now, the only two remaining points are:

> Don't stop for "I stagger" message when running

Hmmm... this would be a bit awkward to implement. An easier fix would be to remove the message. Maybe color the player orange or something instead.

How much of a problem is it that auto walk is not an option while burdened?

> Turn corners in corridors? That would be cool

I'm not sure about this - there's too many questions about how to travel through the corridors exactly. There might even have to be two separate commands ("fastest route", and "safest route"). Considering that IA has pretty small levels, I don't think it's worth the mess to be honest.

**Comment by enormandeau** [comment]
Staggering is a character effect while running is a player QoL feature. If your character is burdened, as a player you still want to be able to navigate the maps without a crazy amount of key presses. Being burdened has in game effect (I guess being slowed down, losing combat effectiveness, etc.) but penalizing the player by deteriorating their playing experience is probably not super... What about (and this may sound funny since I asked for the removal of stopping after a fixed number of turns) if instead you let the character run for 10 turns before stopping for the stagger message? It would keep the remainder and be very slightly annoying but not as disruptive.

For the corridor thing, since we can run in diagonal too, it mitigates the problem a bit. Like you say, it's a can of worms. The kind of thing people say "this should be easy" and you can foresee all kinds of exceptions. I still think that it would be great to have these 3 choices in the options menu 1) don't turn on corners, 2) turn safe, 3) turn fast. Then people can decide what kind of gameplay or compromise they want. Of course, it's your call and it works pretty well now. Thanks for the improvements!

**Comment by martin-tornqvist** [comment]
I'll have to say that it's good enough for now, and revisit this later.

**Comment by enormandeau** [comment]
I think it is much better now.
