### ISSUE TITLE
Look command to view item details from the floor

### ISSUE THREAD

**Issue by enormandeau** [martin-tornqvist/ia#194]
It would be useful for the look (`v`) command to allow us to look at item descriptions when they are on the floor like it does for monsters.

Presently, you have to move to the object, pick up the item, look up its description, then drop it... That's a lot of key presses that a simple `v` would solve.

**Comment by martin-tornqvist** [comment]
Sure that would be nice.

What about the situation where a monster is standing on an item though?

**Comment by enormandeau** [comment]
Options:
1. Player can only view the monster
2. Player can choose

Option 1 seems to solve 99% of the problems.

Option 2. Add a `is_viewable` trait to things. When using `v` on a cell with more than one, open a pop-up listing possible choices with a, b, c... like in the inventory when we choose a weapon for slots a or b.

**Comment by martin-tornqvist** [comment]
Issue imported to GitLab
