### ISSUE TITLE
Crash on unhandled exception: "array too small" error from map generation

### ISSUE THREAD

**Issue by MichealMcErlean** [martin-tornqvist/ia#195]
Built IA on the develop fork through CMake on Visual Studio Community 2017. Getting this bug on attempting to enter the first level. The exception is being thrown from an external dependency named 'xutility'.

Unhandled exception at 0x0FF6CAB6 (ucrtbased.dll) in ia.exe: An invalid parameter was passed to a function that considers invalid parameters fatal.

Call stack is as below:
![image](https://user-images.githubusercontent.com/17152376/32399307-09d0567c-c149-11e7-8919-ccd25a1b62de.png)

Affected code is as below:
![image](https://user-images.githubusercontent.com/17152376/32399375-7ad02cf8-c149-11e7-9cd0-61f993f5d6d8.png)

Built and ran the debug solution, and the issue appears to be spawning stairs at the start location for the first floor:
![image](https://user-images.githubusercontent.com/17152376/32399527-d5d33a4a-c14a-11e7-95eb-92d2f68fa2d2.png)

**Comment by martin-tornqvist** [comment]
That last message is printed when mk_stairs() returns - so this issue occurs after the stairs are placed, before the next thing is printed.

**Comment by martin-tornqvist** [comment]
Well your callstack points out exactly where it happens, it's the call to copy_n on line 541 in mapgen_utils.cpp

I don't think I'm calling copy_n correctly. I'll change it to a memcpy instead, that's that I'm doing in some other cases anyway.

**Comment by MichealMcErlean** [comment]
Glad the extra info helped.

**Comment by martin-tornqvist** [comment]
Try it out now: 585565fb6aaccd4053049b1bc8d1ae0294bb7243

**Comment by MichealMcErlean** [comment]
Okay, that appears to have fixed this one. Level one loads correctly, both
with and without the intro area.

**Comment by martin-tornqvist** [comment]
Excellent.
