### ISSUE TITLE
Discovering ghouls plays sounds associated with wolfs

### ISSUE THREAD

**Issue by iamstevevan** [martin-tornqvist/ia#198]
TL;DR
Wolf sound played when ghouls were alerted.  No wolves present.

Dungeon crawling and opened a door.  Enemies in the dark were alerted and the wolf howl noise was played.  "Easy", I thought as I snuck to a near corner, awaiting canines to stab.  Suddenly, multiple ghouls were upon me. I fought valiantly and narrowly won to explore the (closed) room they were in when to my surprise no wolves were found. Had I know they were ghouls, I would have run.

**Comment by martin-tornqvist** [comment]
This is intentional. They are supposed to be wolf/dog-like creatures, and I like that some things may not be exactly what you think.
