### ISSUE TITLE
Misleading appearance of grates (looks like they are made of wood)

### ISSUE THREAD

**Issue by iamstevevan** [martin-tornqvist/ia#199]
Wooden doors (and frames) are burnable, but grates (which appears wooden) are not.

**Comment by martin-tornqvist** [comment]
They are actually metal - but I see they are brown, which I now realize make them appear to be made of wood. I rather think their appearance should be fixed to make them look more like metal, and maybe they should also be called "metal grate" or something.

**Comment by iamstevevan** [comment]
"Wood" it be possible to have two types of grates? One metal without
possibility to be burned and one wood that can be burned? Both possible to
be blown up via dynamite?

**Comment by martin-tornqvist** [comment]
Sure. I suppose the wooden variant would also be kickable.

**Comment by iamstevevan** [comment]
Awesome! Keep up the great work

**Comment by martin-tornqvist** [comment]
Issue imported to GitLab
