### ISSUE TITLE
Various player actions are not muted when deaf

### ISSUE THREAD

**Issue by iamstevevan** [martin-tornqvist/ia#200]
Stepped on a deafening trap and turned on my lantern (made a sound) to pick up a potion (also made a sound).

If I am deaf, should these be audible?

**Comment by martin-tornqvist** [comment]
When you are deaf, all in-game sounds are blocked. The lantern sound and potion pickup sounds are just interface effects - they have no impact on gameplay.

With that said, it could be more atmospheric to not play any audio at all while you're death, to really emphasize the silence.

**Comment by iamstevevan** [comment]
Should mention reloading sound occurs when deaf. If an enemy were nearby, could they hear that and be alerted?

**Comment by martin-tornqvist** [comment]
I checked, and reloading doesn't actually produce an in-game sound. It simply plays the reload sound effect audio.

It really should make an in-game sound though.

**Comment by martin-tornqvist** [comment]
Issue imported to GitLab
