### ISSUE TITLE
Cannot throw item (throwing knife) over cleared alchemist_bench

### ISSUE THREAD

**Issue by iamstevevan** [martin-tornqvist/ia#201]
The default icon for alchemist_bench seems to indicate that the height would prevent throwing items over/through it and the game prevents this action (red throwing status). 

When items are gathered (if any) from alchemist_bench, icon changes and shows reduced height, making player thing that throwing over/through is possible but the game prevents this action (red throwing status).

**Comment by martin-tornqvist** [comment]
I suppose it might as well always allow throwing through it.

**Comment by martin-tornqvist** [comment]
Issue imported to GitLab
