### ISSUE TITLE
Throwing items at switches

### ISSUE THREAD

**Issue by iamstevevan** [martin-tornqvist/ia#205]
Enhancement request: Being able to throw an object to toggle a switch
Reason: switches for Pylons could be activated so that you could burn out a room full of baddies without entering all the way in and running out.

**Glitch: In 19.2 this doesn't exists and causes the thrown object to disappear (does not appear on any tile)**

**Comment by martin-tornqvist** [comment]
From a gameplay perspective, this sounds kind of fun. But I think it's too much of a stretch to imagine switching a rusty metal lever by throwing a knife at it.

That glitch should be fixed though, I'll check it out.

**Comment by iamstevevan** [comment]
Fair enough, although throwing a sledge is possible. Thanks again for such a great game with high replay-ability (literally multiple rounds a day!)

**Comment by martin-tornqvist** [comment]
Issue imported to GitLab
