### ISSUE TITLE
No saved game found

### ISSUE THREAD

**Issue by Kzer-Za** [martin-tornqvist/ia#206]
When descending the second stairs, I chose to save the game. Then, without quitting, I tried to "Resurrect" from the main menu. The game just gave me "No saved game found".

I have a suggestion why this could happen. Perhaps, your game keeps the saves relative to the binary? I have not downloaded it from your site, but installed it from AUR (I have Manjaro Linux), so it's installed not in my home folder, but in `/opt`. Of course, I don't have the write access to `/opt/infra-arcana`, so *if* it tries to create a save there, it would fail.

If I'm wrong about the cause, I will try to provide additional information.

**Comment by Kzer-Za** [comment]
It seems I was right about the cause of this bug. I created an empty file `~/.config/infra-arcana/save` and then did `sudo ln -s ~/.config/infra-arcana/save /var/lib/infra-arcana/data/save` (because `/opt/infra-arcana/res/data` is a link to `/var/lib/infra-arcana/data`), and now saving works.

Nevertheless, please, make the game use save directory in home by default.

**Comment by martin-tornqvist** [comment]
>Nevertheless, please, make the game use save directory in home by default.

On Linux (and OSX), but not on Windows, right?

What directory should be used exactly? `$HOME/infra-arcana` ?

Another solution I considered was to use an environment variable for user files like save games and game config, such as `IA_USER_DIR`. If this variable is not set, these files will be stored relative to the binary by default.

Also, note that the project has been moved to GitLab (I should probably disable issues on GitHub if that's possible):

https://gitlab.com/martin-tornqvist/ia

**Comment by martin-tornqvist** [comment]
Added GitLab issue for this (with a reference back to this issue):

https://gitlab.com/martin-tornqvist/ia/issues/213

**Comment by martin-tornqvist** [comment]
There is a solution implemented and added on GitLab now, see https://gitlab.com/martin-tornqvist/ia/issues/213.

This issue is redundant, closing.
