### ISSUE TITLE
GCC 4.9 compilation

### ISSUE THREAD

**Issue by orbisvicis** [martin-tornqvist/ia#80]
Looking forward to playing v17! Looks like gcc 4.9 requires extra includes:

`include/FeatureData.h`

```
#include <functional>
```

[kwin: build failure with gcc-4.9.0](http://mail.kde.org/pipermail/plasma-devel/2014-April/030608.html)

**Comment by InfraArcana** [comment]
Thanks for the heads-up

**Comment by martin-tornqvist** [comment]
Wow, this is an old issue. It's no longer relevant.
