### ISSUE TITLE
Oddity in damage calculation formula

### ISSUE THREAD

**Issue by ethanfine** [martin-tornqvist/ia#95]
In attack.cpp Melee_att_data::Melee_att_data, it seems as though dmg_dice.plus is only added when the attack is weak or a critical hit. In the normal case it sets dmg equal to rnd::dice(dmg_dice) which does not refer to p.plus. So it would seem, in the case of a regular hit, the plus bonus is ignored.

I first noticed the behavior when I noticed a +4 dagger still did not kill rat things in one hit typically, 

Is this intended behavior, a bug, or am I missing something?

**Comment by martin-tornqvist** [comment]
Holy shit, yeah I think you're right! It seems there is an error in the rnd::dice() which takes the Dice_param. The dice function is probably supposed to add the "plus" value from the parameter to the result.
This affects ranged attacks as well.

Great find! thank you! This could have gone unnoticed a long time.

**Comment by martin-tornqvist** [comment]
It would be good to do a search for all places that uses rnd::dice(), and check if the caller seems to assume that the dice function adds the plus value.  (Perhaps the caller does it somewhere, in that case the plus would be added twice if rnd::dice() were fixed).

**Comment by ethanfine** [comment]
So I did a search, and didn't find any places where the caller adds the plus value, but I'm not necessarily confident.

If I was going to submit a patch to fix this issue, I would:
1. Add a method roll to dice_param, and remove rnd::dice(dice_param)
2. Add a method min to dice_param, and use it for calculating weakened damage etc.
3. Ensure that "plus" is never explicitly used in formulas, always max, roll, or min.

This would have the benefit of letting us be confident we didn't make an error, and also I think it would formulas easier to read.

If you want I can make a pull request that does this.

**Comment by martin-tornqvist** [comment]
Sounds like good suggestions. Feel free to do it if you want. To implement
it, cmn_types.cpp needs to be added, and should be included in the
codeblocks project too.

Perhaps the rnd namespace should not provide or talk about dice stuff at
all. So it would just be more basic functions there.

So I did a search, and didn't find any places where the caller adds the
plus value, but I'm not necessarily confident.

If I was going to submit a patch to fix this issue, I would:
1. Add a method roll to dice_param, and remove rnd::dice(dice_param)
2. Add a method min to dice_param, and use it for calculating weakened
damage etc.
3. Ensure that "plus" is never explicitly used in formulas, always max,
roll, or min.

This would have the benefit of letting us be confident we didn't make an
error, and also I think it would formulas easier to read.

If you want I can make a pull request that does this.

—
Reply to this email directly or view it on GitHub
<https://github.com/martin-tornqvist/ia/issues/95#issuecomment-162868679>.

**Comment by martin-tornqvist** [comment]
It would be somewhat inconsequential that dice are handled differently from
e.g. fractions though (for dice you call on the Dice_param object, while
for fractions you'd call the rnd namespace).... hm
