### ISSUE TITLE
Rat things trigger phobia of the dead

### ISSUE THREAD

**Issue by hubertig** [martin-tornqvist/ia#98]
I assume they're not undead, so it's probably a bug.

**Comment by martin-tornqvist** [comment]
Good call, thanks! This is totally a bug.

**Comment by martin-tornqvist** [comment]
The problem was that Phobia of the dead did not check if the monster is undead - it checked if the monster is a **rat**! (copy/paste error)

Fixed by f96501570324990f287b7a76edfb04284d21ef98
